env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/jsx-runtime
  - plugin:import/typescript
  - plugin:import/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - import
settings:
  import/resolver:
    typescript:
      project: './tsconfig.json'
rules:
  import/no-unresolved: 'error'
  import/order:
    - 'error'
    - groups:
        - 'builtin'
        - 'external'
        - 'internal'
        - - 'sibling'
          - 'parent'
        - 'index'
        - 'unknown'
      'newlines-between': 'always'
      alphabetize:
        order: 'asc'
        caseInsensitive: true
